global_costmap:
  global_frame: map
  rolling_window: true # true required for rrt_exploration
  width: 100.0
  height: 100.0
  static_map: true
  resolution: 0.05
  obstacle_layer:
    enabled: false
  inflation_layer:
    inflation_radius: 1.0
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}